services:
  client:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: 
      - sh
      - -c
      - >
        npm install &&
        npm run dev:host
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - unifider_network

networks:
  unifider_network:
    external: true
