services:
  client:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
    networks:
      - unifider_network  

networks:
  unifider_network: 
    external: true 
