services:
  db:
    image: postgres:17.4
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: unifider_db
    volumes:
      - ./postgres:/var/lib/postgresql/data