name: Bearer CLI Code Scanning

on:
  pull_request:
    branches:
      - master
      - dev

permissions:
  contents: read
  security-events: write

jobs:
  bearer_scan_client:
    name: Bearer Scan (Client)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bearer CLI on Client
        uses: bearer/bearer-action@v2
        with:
          directory: client/
          args: "--format=rdjson --output=bearer-client-results.rdjson"
        continue-on-error: true

      - name: Upload Bearer Client results to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: client/bearer-client-results.rdjson
          category: bearer-client

  bearer_scan_server:
    name: Bearer Scan (Server)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bearer CLI on Server
        uses: bearer/bearer-action@v2
        with:
          directory: server/
          args: "--format=rdjson --output=bearer-server-results.rdjson"
        continue-on-error: true

      - name: Upload Bearer Server results to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: server/bearer-server-results.rdjson
          category: bearer-server
