name: Bearer CLI Code Scanning

# Este workflow se ejecutará en cada push y Pull Request
on:
  pull_request:
    branches:
      - master
      - dev

# Permisos necesarios para que GitHub Actions pueda leer el código
# y escribir eventos de seguridad (las alertas de Code Scanning)
permissions:
  contents: read
  security-events: write # Permiso crucial para que las alertas aparezcan en la pestaña Security

jobs:
  bearer_scan_client:
    name: Bearer Scan (Client)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bearer CLI on Client
        uses: bearer/bearer-action@v2
        with:
          directory: client/ # Directorio donde se encuentra el código del cliente
          # Genera el reporte en formato RDJSON (compatible con SARIF)
          # y lo guarda en un archivo llamado bearer-client-results.rdjson
          args: "--format=rdjson --output=bearer-client-results.rdjson"

      - name: Upload Bearer Client results to Code Scanning
        uses: github/codeql-action/upload-sarif@v3 # Acción oficial de GitHub para subir resultados SARIF
        with:
          sarif_file: bearer-client-results.rdjson # Ruta al archivo de resultados generado por Bearer
          category: bearer-client # Una categoría para identificar estos resultados en GitHub (ej. "bearer-client")
          # Nota: Esta acción sube los resultados. No falla el workflow por las alertas encontradas.

  bearer_scan_server:
    name: Bearer Scan (Server)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bearer CLI on Server
        uses: bearer/bearer-action@v2
        with:
          directory: server/ # Directorio donde se encuentra el código del servidor
          # Genera el reporte en formato RDJSON (compatible con SARIF)
          # y lo guarda en un archivo llamado bearer-server-results.rdjson
          args: "--format=rdjson --output=bearer-server-results.rdjson"

      - name: Upload Bearer Server results to Code Scanning
        uses: github/codeql-action/upload-sarif@v3 # Acción oficial de GitHub para subir resultados SARIF
        with:
          sarif_file: bearer-server-results.rdjson # Ruta al archivo de resultados generado por Bearer
          category: bearer-server # Una categoría para identificar estos resultados en GitHub (ej. "bearer-server")
          # Nota: Esta acción sube los resultados. No falla el workflow por las alertas encontradas.
