name: Restrict PRs to Main

on:
  pull_request:
    branches:
      - 'master'

jobs:
  check_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR Source Branch
        id: branch_check
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          BASE_BRANCH="${{ github.base_ref }}"

          if [ "$BASE_BRANCH" == "master" ] && [ "$SOURCE_BRANCH" != "dev" ]; then
            echo "::error file=.github/workflows/restrict-main-pr.yml::Pull Requests to 'main' are only allowed from 'dev' branch. Please rebase your changes onto 'dev' and open a PR from 'dev' to 'main'."
            exit 1
          else
            echo "Source branch is valid for this Pull Request."
          fi